apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f SonarQube.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "5432"
      port: {{ .Values.dbPort }}
      targetPort: {{ .Values.dbPort }}
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
