apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f SonarQube.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarqube
  name: sonarqube
spec:
  ports:
    - name: "9000"
      port: {{ .Values.sonarPort }}
      protocol: TCP
      targetPort: {{ .Values.sonarPort }}

  selector:
    io.kompose.service: sonarqube
status:
  loadBalancer: {}
